hotgluexyz/tap-chargebee

setup.py
tap_chargebee/schemas/customers.json

Add ability to pull relationship field on customers.

---

tap_chargebee/schemas/subscriptions.json

- Add unit_price_in_decimal to Subscription stream

add field to subscriptions schema

---

setup.py
tap_chargebee/schemas/item_families.json
tap_chargebee/streams/__init__.py
tap_chargebee/streams/item_families.py

- Add a new stream item_families

add stream item_families

---

tap_chargebee/schemas/customers.json
tap_chargebee/schemas/invoices.json
tap_chargebee/schemas/items.json
tap_chargebee/schemas/plans.json
tap_chargebee/schemas/subscriptions.json

- Add channel column to streams

add channel column

---

tap_chargebee/schemas/addons.json
tap_chargebee/schemas/credit_notes.json

- Add channel to credit notes and addons
[Linear Task](https://linear.app/hotglue/issue/HGI-2702/[revlock]-add-channel-column-to-tap-chargebee-streams)

add fields

---

tap_chargebee/schemas/item_prices.json

changed schema to add custom field'

---

tap_chargebee/schemas/item_prices.json

Custom fields for item prices

---

setup.py
tap_chargebee/schemas/item_prices.json

Custom fields support for item_prices stream

---

tap_chargebee/schemas/credit_notes.json
tap_chargebee/schemas/invoices.json

adding new fields to 2 streams
```
sub_total_in_local_currency
total_in_local_currency
local_currency_code
local_currency_exchange_rate
```

added new fields to credit-notes and invoices

---

tap_chargebee/schemas/usages.json
tap_chargebee/streams/__init__.py
tap_chargebee/streams/base.py
tap_chargebee/streams/usages.py

Adds usages as a child stream for Subscriptions

---

tap_chargebee/streams/base.py
tap_chargebee/streams/usages.py

Changes way of iterating through child_records on sync_data function

---

tap_chargebee/schemas/usages.json
tap_chargebee/streams/usages.py

Fixes schema

---

tap_chargebee/client.py

Tag 129 betterlogs

---

tap_chargebee/schemas/invoices.json

New properties for Invoices stream HGI-5756.

---

tap_chargebee/schemas/invoices.json

Invoice new property local_currency_exchange_rate

---

tap_chargebee/streams/base.py

1. Fetch all transactions by update_at and date
2. Remove filtering by status for transactions

Fetch all transactions by update_at and by date 

---

tap_chargebee/client.py

Skip non supported streams.

---

tap_chargebee/schemas/invoices.json

generated_at for invoices

---

tap_chargebee/schemas/credit_notes.json

Generated at for credit notes stream.

---

tap_chargebee/schemas/unbilled_charges.json

business_entity_id for unbilled_charges stream.

---

tap_chargebee/schemas/events.json
tap_chargebee/streams/base.py

Add fields to events.subscriptions
Add filter by event_types 
- 
- 

add fields and filter by event_types

---

tap_chargebee/schemas/credit_notes.json
tap_chargebee/streams/credit_notes.py

HG-3421 / Add fields to CreditNotesStream's schema

---

tap_chargebee/client.py
tap_chargebee/streams/base.py
tap_chargebee/streams/util.py

HGI-6533 / Add entity filters

---

tap_chargebee/streams/base.py

add date[before] filter in transactions `sync_by_date` logic

add date[before] filter in transactions sync_by_date logic

---

tap_chargebee/streams/base.py

use date as bookmark key when sync_by_date

use date as bookmark key when sync_by_date

---

tap_chargebee/streams/base.py

add use_end_date flag

---

.vscode/.gitignore
tap_chargebee/schemas/customers.json

HGI-6902 / Add active_id to customers stream

---

tap_chargebee/streams/__init__.py

move price_variants and ramps to AVAILABLE_STREAMS_2_0_ONLY
- 
- 

move price_variants and ramps to only v2

---

tap_chargebee/schemas/item_prices.json

HGI-6850 / Fix capitalize for cf_RevRec_LOC_Name

---

.gitignore
tap_chargebee/state.py

HGI-7055 added 1s to bookmark_date every time

---

.github/workflows/smoke-test.yml
.gitignore
tap_chargebee/streams/base.py
tap_chargebee/streams/usages.py

https://linear.app/hotglue/issue/HGI-7649/[revlock]-make-historical-batch-interval-configurable-for-tap
- 
- 

feat(HGI-7649): support configurable batch size

---

tap_chargebee/streams/invoices.py

- Chargebee has changed how line items are retrieved to support invoices with a very large number of lines
- 
- 

HGI-7623: Add support for retrieving all line items for invoices

---

tap_chargebee/streams/base.py
tap_chargebee/streams/usages.py

fix: infinite loop in UsagesStream sync_data method
